export enum ListNames {
    Employee = "Employee",
    ProjectSubmissionReport = "Project Submission Report",
    AnnualPASubmissionReport = "Annual PA Submission Report",
    Designation = "Designation",
    PAProcess = "PA Process",
    FinancialYear = "FinancialYear",
    Subcategory = "Subcategory",
    DMSDocuments = "DMS Documents",
    DMSDocumentsPath = "DMSDocuments",
    ExcelClientList = "Excel Client List",
    TableEdit = "TableEdit",
    SharedDocumentsPath = "Shared Documents",
    ErrorLog = "ErrorLog",

    // Drug Management System (UI: Admin / Author / Reviewer / Approver)
    Categories = "Categories",
    Templates = "Templates",
    Documents = "Documents",
    SignedDocuments = "Signed Documents",
    CTDFolders = "CTD Folder Structure",
    DrugsDatabase = "Drugs Database",
    EctdSections = "eCTD Sections",
    GmpModels = "GMP Models",
    Mappings = "Mappings",
    Departments = "Departments",
    Employees = "Employees",
    UserRolesPermissions = "User Roles Permissions",
    WorkflowsApprovals = "Workflows Approvals",
    AuditLogs = "Audit Logs",
    TMFFolders = "TMF Folder Structure",
    Countries = "Countries",
    GmpCategories = "GMP Categories",
    TmfZones = "TMF Zones",
    eSignature = 'eSignature',
    ProjectDocuments = "Project Documents"
}